apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.mongodb.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.db.mongodb.label }}
  ports:
    - protocol: TCP
      port: 27017
