apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.api.name }}
spec:
  selector:
    app: {{ .Values.controller.api.label }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
